const map=L.map('map',{zoomControl:false}).setView([13.7563,100.5018],11);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
const layers={cctv:L.layerGroup().addTo(map),flood:L.layerGroup().addTo(map),slidecar:L.layerGroup().addTo(map)};const enabled={cctv:true,flood:true,slidecar:true};let data={cctv:[],flood:[],slidecar:[]},searchMarker=null,searchController=null;
const districts=['พระนคร','ดุสิต','หนองจอก','บางรัก','บางเขน','บางกะปิ','ปทุมวัน','ป้อมปราบศัตรูพ่าย','พระโขนง','มีนบุรี','ลาดกระบัง','ยานนาวา','สัมพันธวงศ์','พญาไท','ธนบุรี','บางกอกใหญ่','ห้วยขวาง','คลองสาน','ตลิ่งชัน','บางกอกน้อย','บางขุนเทียน','ภาษีเจริญ','หนองแขม','ราษฎร์บูรณะ','บางพลัด','ดินแดง','บึงกุ่ม','สาทร','บางซื่อ','จตุจักร','บางคอแหลม','ประเวศ','คลองเตย','สวนหลวง','จอมทอง','ดอนเมือง','ราชเทวี','ลาดพร้าว','วัฒนา','บางแค','หลักสี่','สายไหม','คันนายาว','สะพานสูง','วังทองหลาง','คลองสามวา','บางนา','ทวีวัฒนา','ทุ่งครุ','บางบอน'];
const ds=document.querySelector('#district'),qel=document.querySelector('#q'),searchForm=document.querySelector('#map-search'),searchSubmit=searchForm.querySelector('button'),status=document.querySelector('#status'),feedback=document.querySelector('#layer-feedback'),feedbackText=document.querySelector('#layer-feedback-text'),feedbackAction=document.querySelector('#layer-feedback-action');const layerNames={cctv:'CCTV',flood:'น้ำท่วม',slidecar:'รถสไลด์'};districts.sort((a,b)=>a.localeCompare(b,'th')).forEach(x=>ds.add(new Option(x,x)));const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function matches(x){const d=ds.value,q=qel.value.trim().toLowerCase();return(!d||x.district===d)&&(!q||`${x.name||''} ${x.road||''} ${x.district||''} ${x.area||''} ${x.phone||''}`.toLowerCase().includes(q))}
function popup(x,type){let b=`<b>${esc(x.name||'ไม่ระบุชื่อ')}</b><br>${esc(x.district||'')} ${esc(x.road||x.area||'')}`;if(x.phone)b+=`<br>☎ <a href="tel:${esc(x.phone)}">${esc(x.phone)}</a>`;if(x.note)b+=`<br><small>${esc(x.note)}</small>`;if(x.source)b+=`<br><small>แหล่งข้อมูล: ${esc(x.source)}</small>`;if(x.image)b+=`<br><img loading="lazy" referrerpolicy="no-referrer" src="${esc(x.image)}" alt="CCTV">`;if(x.url)b+=`<br><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">เปิดแหล่งข้อมูล ↗</a>`;return b}
function validPoints(type){return data[type].filter(x=>Number.isFinite(+x.lat)&&Number.isFinite(+x.lng))}
function render(){Object.values(layers).forEach(l=>l.clearLayers());let counts={cctv:0,flood:0,slidecar:0};for(const type of Object.keys(data)){if(enabled[type])data[type].filter(matches).forEach(x=>{if(!Number.isFinite(+x.lat)||!Number.isFinite(+x.lng))return;counts[type]++;const color=type==='cctv'?(x.online===false?'#6b7280':'#047857'):type==='flood'?'#2563eb':'#ea580c';L.circleMarker([+x.lat,+x.lng],{radius:type==='cctv'?7:8,weight:2,color,fillOpacity:.88}).bindPopup(popup(x,type)).addTo(layers[type])});const button=document.querySelector(`[data-layer="${type}"]`);button.querySelector('.pill-count').textContent=validPoints(type).length.toLocaleString('th-TH');button.setAttribute('aria-label',`${layerNames[type]} ${enabled[type]?'เปิด':'ปิด'} มี ${validPoints(type).length} จุด`)}const summary=Object.keys(data).map(type=>`${layerNames[type]} ${enabled[type]?counts[type].toLocaleString('th-TH')+' จุด':'ปิด'}`).join(' · ');status.textContent=summary+(qel.value.trim()&&!Object.values(counts).some(Boolean)?' · กด “ค้นหา” เพื่อค้นหาสถานที่บนแผนที่':'')}
function showLayerFeedback(type){const total=validPoints(type).length;if(!enabled[type]){feedbackText.textContent=`ปิดเลเยอร์ ${layerNames[type]} แล้ว`;feedbackAction.hidden=true}else if(total){feedbackText.textContent=`เปิดเลเยอร์ ${layerNames[type]} แล้ว พบ ${total.toLocaleString('th-TH')} จุด`;feedbackAction.hidden=true}else{feedbackText.textContent=`ยังไม่มีจุด${layerNames[type]}ที่ยืนยันพิกัดบนแผนที่`;feedbackAction.hidden=false;feedbackAction.textContent=type==='slidecar'?'ดูสายด่วนฉุกเฉิน':'ดูแหล่งข้อมูลต้นทาง';feedbackAction.onclick=()=>window.dispatchEvent(new CustomEvent('open-resource-category',{detail:type==='slidecar'?'emergency':type==='cctv'?'cctv':'water'}))}feedback.classList.add('show');clearTimeout(showLayerFeedback.timer);showLayerFeedback.timer=setTimeout(()=>feedback.classList.remove('show'),7000)}
async function searchPlace(event){event.preventDefault();const term=qel.value.trim();if(!term){feedbackText.textContent='กรุณาพิมพ์ชื่อถนน แยก หรือสถานที่';feedbackAction.hidden=true;feedback.classList.add('show');qel.focus();return}searchController?.abort();searchController=new AbortController();searchSubmit.disabled=true;searchSubmit.textContent='กำลังค้น…';feedback.classList.remove('show');try{const area=ds.value?`, ${ds.value}`:'';const params=new URLSearchParams({q:`${term}${area}, กรุงเทพมหานคร, ประเทศไทย`,format:'jsonv2',limit:'1',countrycodes:'th',viewbox:'100.327,13.955,100.938,13.493',bounded:'1','accept-language':'th'});const response=await fetch(`https://nominatim.openstreetmap.org/search?${params}`,{signal:searchController.signal,headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const [result]=await response.json();if(!result){feedbackText.textContent=`ไม่พบสถานที่ “${term}” ลองใช้ชื่อถนนหรือแยกที่สั้นลง`;feedbackAction.hidden=true;feedback.classList.add('show');return}if(searchMarker)map.removeLayer(searchMarker);const point=[+result.lat,+result.lon];searchMarker=L.marker(point).addTo(map).bindPopup(`<b>ผลการค้นหา</b><br>${esc(result.display_name)}`).openPopup();map.setView(point,16);feedbackText.textContent=`พบ “${term}” และเลื่อนไปยังตำแหน่งแล้ว`;feedbackAction.hidden=true;feedback.classList.add('show')}catch(error){if(error.name!=='AbortError'){feedbackText.textContent='ค้นหาสถานที่ไม่ได้ในขณะนี้ กรุณาลองอีกครั้ง';feedbackAction.hidden=true;feedback.classList.add('show');console.warn('Place search failed',error)}}finally{searchSubmit.disabled=false;searchSubmit.textContent='ค้นหา'}}
ds.onchange=render;qel.oninput=render;searchForm.onsubmit=searchPlace;document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{const t=b.dataset.layer;enabled[t]=!enabled[t];b.classList.toggle('active',enabled[t]);b.setAttribute('aria-pressed',String(enabled[t]));render();showLayerFeedback(t)});document.querySelector('#locate').onclick=()=>map.locate({setView:true,maxZoom:15});map.on('locationfound',e=>L.circleMarker(e.latlng,{radius:8,color:'#7c3aed',fillOpacity:.9}).bindPopup('ตำแหน่งโดยประมาณของคุณ').addTo(map).openPopup());
async function getJSON(path){try{const r=await fetch(path,{cache:'no-store'});return r.ok?await r.json():[]}catch(e){console.warn(path,e);return[]}}
async function load(){const [c,f,s]=await Promise.all([getJSON('./data/cameras.json'),getJSON('./data/flood.json'),getJSON('./data/slidecars.json')]);data={cctv:c,flood:f,slidecar:s};render()}load();

