const map=L.map('map',{zoomControl:false}).setView([13.7563,100.5018],11);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
const layers={cctv:L.layerGroup().addTo(map),flood:L.layerGroup().addTo(map),slidecar:L.layerGroup().addTo(map)};const enabled={cctv:true,flood:true,slidecar:true};let data={cctv:[],flood:[],slidecar:[]};
const districts=['พระนคร','ดุสิต','หนองจอก','บางรัก','บางเขน','บางกะปิ','ปทุมวัน','ป้อมปราบศัตรูพ่าย','พระโขนง','มีนบุรี','ลาดกระบัง','ยานนาวา','สัมพันธวงศ์','พญาไท','ธนบุรี','บางกอกใหญ่','ห้วยขวาง','คลองสาน','ตลิ่งชัน','บางกอกน้อย','บางขุนเทียน','ภาษีเจริญ','หนองแขม','ราษฎร์บูรณะ','บางพลัด','ดินแดง','บึงกุ่ม','สาทร','บางซื่อ','จตุจักร','บางคอแหลม','ประเวศ','คลองเตย','สวนหลวง','จอมทอง','ดอนเมือง','ราชเทวี','ลาดพร้าว','วัฒนา','บางแค','หลักสี่','สายไหม','คันนายาว','สะพานสูง','วังทองหลาง','คลองสามวา','บางนา','ทวีวัฒนา','ทุ่งครุ','บางบอน'];
const ds=document.querySelector('#district'),qel=document.querySelector('#q'),status=document.querySelector('#status');districts.sort((a,b)=>a.localeCompare(b,'th')).forEach(x=>ds.add(new Option(x,x)));const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function matches(x){const d=ds.value,q=qel.value.trim().toLowerCase();return(!d||x.district===d)&&(!q||`${x.name||''} ${x.road||''} ${x.district||''} ${x.area||''} ${x.phone||''}`.toLowerCase().includes(q))}
function popup(x,type){let b=`<b>${esc(x.name||'ไม่ระบุชื่อ')}</b><br>${esc(x.district||'')} ${esc(x.road||x.area||'')}`;if(x.phone)b+=`<br>☎ <a href="tel:${esc(x.phone)}">${esc(x.phone)}</a>`;if(x.note)b+=`<br><small>${esc(x.note)}</small>`;if(x.source)b+=`<br><small>แหล่งข้อมูล: ${esc(x.source)}</small>`;if(x.image)b+=`<br><img loading="lazy" referrerpolicy="no-referrer" src="${esc(x.image)}" alt="CCTV">`;if(x.url)b+=`<br><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">เปิดแหล่งข้อมูล ↗</a>`;return b}
function render(){Object.values(layers).forEach(l=>l.clearLayers());let counts={cctv:0,flood:0,slidecar:0};for(const type of Object.keys(data)){if(!enabled[type])continue;data[type].filter(matches).forEach(x=>{if(!Number.isFinite(+x.lat)||!Number.isFinite(+x.lng))return;counts[type]++;const color=type==='cctv'?(x.online===false?'#6b7280':'#047857'):type==='flood'?'#2563eb':'#ea580c';L.circleMarker([+x.lat,+x.lng],{radius:type==='cctv'?7:8,weight:2,color,fillOpacity:.88}).bindPopup(popup(x,type)).addTo(layers[type])})}status.textContent=`CCTV ${counts.cctv.toLocaleString('th-TH')} · น้ำท่วม ${counts.flood.toLocaleString('th-TH')} · รถสไลด์ ${counts.slidecar.toLocaleString('th-TH')} จุด`}
ds.onchange=render;qel.oninput=render;document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{const t=b.dataset.layer;enabled[t]=!enabled[t];b.classList.toggle('active',enabled[t]);render()});document.querySelector('#locate').onclick=()=>map.locate({setView:true,maxZoom:15});map.on('locationfound',e=>L.circleMarker(e.latlng,{radius:8,color:'#7c3aed',fillOpacity:.9}).bindPopup('ตำแหน่งโดยประมาณของคุณ').addTo(map).openPopup());
async function getJSON(path){try{const r=await fetch(path,{cache:'no-store'});return r.ok?await r.json():[]}catch(e){console.warn(path,e);return[]}}
async function load(){const [c,f,s]=await Promise.all([getJSON('./data/cameras.json'),getJSON('./data/flood.json'),getJSON('./data/slidecars.json')]);data={cctv:c,flood:f,slidecar:s};render()}load();